services:
  web:
    image: php:8.3-apache
    ports:
      - "9000:80"
      - "9001:443"
    depends_on:
      - db
    volumes:
      - .:/var/www/html/.
    restart: "no"
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass1
      MYSQL_DATABASE: mccv2
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "9002:8080"
    depends_on:
      - db
    links:
      - web
    environment:
      PMA_HOST: db

# Note:
# If you encounter either mysqli not being found or captcha images not loading, chances are that the docker image was updated and those modules are no longer part of it
# A new image will be built for this so that the dependencies are there and ready for immediate development
# For now, log into the running container's shell - assuming default config, it'll be named something like "mccodesv2-php-web-1"
# Execute the following command:
# apt install libpng-dev -y && docker-php-ext-install mysqli gd
# Optionally, you can also install a couple of useful PHP packages
# docker-php-ext-install mbstring pdo pdo_mysql sockets sodium xsl

# After installation, the extensions should automatically be enabled (where applicable). If not, you can enable them manually.
# docker-php-ext-enable mysqli gd

# Note (cont.)
# Be sure to restart the Apache container to apply your changes!
