services:
  web:
    build:
      context: .
      args:
        - SSL_ENABLED=true
    ports:
      - 9000:80
      - 9001:443
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    environment:
      DB_HOST_FILE: /run/secrets/db_host
      DB_USER_FILE: /run/secrets/db_user
      DB_PASS_FILE: /run/secrets/db_pass
      DB_NAME_FILE: /run/secrets/db_name
      APP_KEY_FILE: /run/secrets/app_key
    secrets:
      - db_host
      - db_user
      - db_pass
      - db_name
      - app_key
    develop:
      watch:
       - action: sync
         path: .
         target: /var/www/html
         ignore:
           - vendor/
  db:
    image: mysql:8.4.0
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
      - ./db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./db/initial_data.sql:/docker-entrypoint-initdb.d/02-initial_data.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 10s
      timeout: 15s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_pass
      MYSQL_DATABASE_FILE: /run/secrets/db_name
    secrets:
      - db_pass
      - db_name
secrets:
  db_host:
    file: docker/secrets/db_host.txt
  db_user:
    file: docker/secrets/db_user.txt
  db_pass:
    file: docker/secrets/db_pass.txt
  db_name:
    file: docker/secrets/db_name.txt
  app_key:
    file: docker/secrets/app_key.txt
volumes:
  db_data:
